name: build-check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          java-package: jdk+fx
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - run: sbt -v update compile
